[project]
name = "gaide"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "django>=6.0.1",
    "httpx>=0.28.1",
    "pydantic>=2.12.5",
    "pydantic-ai>=1.44.0",
    "uvicorn[standard]>=0.40.0",
]
